/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ReferenceId = IDL.Nat;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PromoVideo = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'referenceId' : ReferenceId,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPortfolioItem' : IDL.Func(
      [ReferenceId, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'deletePortfolioItem' : IDL.Func([ReferenceId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPortfolio' : IDL.Func([], [IDL.Vec(PromoVideo)], ['query']),
  'getPortfolioItem' : IDL.Func(
      [ReferenceId],
      [IDL.Opt(PromoVideo)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updatePortfolioItem' : IDL.Func(
      [ReferenceId, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ReferenceId = IDL.Nat;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PromoVideo = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'referenceId' : ReferenceId,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPortfolioItem' : IDL.Func(
        [ReferenceId, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'deletePortfolioItem' : IDL.Func([ReferenceId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPortfolio' : IDL.Func([], [IDL.Vec(PromoVideo)], ['query']),
    'getPortfolioItem' : IDL.Func(
        [ReferenceId],
        [IDL.Opt(PromoVideo)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updatePortfolioItem' : IDL.Func(
        [ReferenceId, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };