/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ReferenceId = IDL.Nat;
export const PromoVideoRequest = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'referenceId' : ReferenceId,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'createPromoVideoRequest' : IDL.Func(
      [ReferenceId, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getAllPromoVideoRequests' : IDL.Func(
      [],
      [IDL.Vec(PromoVideoRequest)],
      ['query'],
    ),
  'getPromoVideoRequest' : IDL.Func(
      [ReferenceId],
      [PromoVideoRequest],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ReferenceId = IDL.Nat;
  const PromoVideoRequest = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'referenceId' : ReferenceId,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'createPromoVideoRequest' : IDL.Func(
        [ReferenceId, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllPromoVideoRequests' : IDL.Func(
        [],
        [IDL.Vec(PromoVideoRequest)],
        ['query'],
      ),
    'getPromoVideoRequest' : IDL.Func(
        [ReferenceId],
        [PromoVideoRequest],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };